export const GET_TESTIMONIALS = 'GET_TESTIMONIALS';
export const SET_TESTIMONIALS = 'SET_TESTIMONIALS';
export const GET_PROFILE = 'GET_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_DASHBOARD = 'SET_DASHBOARD';
export const GET_DASHBOARD = 'GET_DASHBOARD';
