export const GET_PACKAGEDETAILS = 'GET_PACKAGEDETAILS';
export const SET_PACKAGEDETAILS = 'SET_PACKAGEDETAILS';
export const APPLY_PROMOCODE = 'APPLY_PROMOCODE';
export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const CHECKOUT = 'CHECKOUT';
export const MAKE_PURCHASE = 'MAKE_PURCHASE';
export const REMOVE_PROMOCODE = 'REMOVE_PROMOCODE';
